job-service:
  url: http://job-service
company-service:
  url: http://company-service
review-service:
  url: http://review-service:8083

server:
  port: 8082

spring:
  application:
    name: job-service

# H2 Database
#  h2:
#    console:
#      enabled: true
#  datasource:
#    url: jdbc:h2:mem:test

  # Postgres
  datasource:
    url: jdbc:postgresql://postgres:5432/jobportal
    username: admin
    password: password

  jpa:
    database: POSTGRESQL
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    generate-dll: true
    hibernate:
      ddl-auto: update

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false