services:
  postgres:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_MAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - postgres
    restart: unless-stopped

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - postgres

  service-reg:
    image: service-reg
    container_name: service-reg
    ports:
      - 8761:8761
    depends_on:
      - rabbitmq
      - postgres
      - pgadmin
    networks:
      - microservice-network
      - postgres

  company-service:
    image: company-service
    container_name: company-service
    ports:
      - 8081:8081
    depends_on:
      - service-reg
    networks:
      - microservice-network
      - postgres
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - EUREKA_CLIENT_SERVICE_DEFAULTZONE=http://service-reg:8761/eureka

  job-service:
    image: job-service
    container_name: job-service
    ports:
      - 8082:8082
    depends_on:
      - service-reg
    networks:
      - microservice-network
      - postgres
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - EUREKA_CLIENT_SERVICE_DEFAULTZONE=http://service-reg:8761/eureka

  review-service:
    image: review-service
    container_name: review-service
    ports:
      - 8083:8083
    depends_on:
      - service-reg
    networks:
      - microservice-network
      - postgres
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - EUREKA_CLIENT_SERVICE_DEFAULTZONE=http://service-reg:8761/eureka

  gateway:
    image: gateway
    ports:
      - 8084:8084
    depends_on:
      - service-reg
    networks:
      - microservice-network
      - postgres
    environment:
      - SPRING_PROFILES_ACTIVE=docker

networks:
  postgres:
    driver: bridge
  microservice-network:
    driver: bridge

volumes:
  postgres:
  pgadmin: