server:
  port: 8084

spring:
  application:
    name: gateway

  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: company_service
              uri: http://company-service:8081
              predicates:
                - Path=/companies/**
            - id: job_service
              uri: http://job-service:8082
              predicates:
                - Path=/jobs/**
            - id: review_service
              uri: http://review-service:8083
              predicates:
                - Path=/reviews/**

eureka:
  client:
    serviceUrl:
      defaultZone: http://service-reg:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

logging:
  level:
    root: info
    org:
      springframework:
        cloud:
          gateway: INFO