job-service:
  url: http://job-service
company-service:
  url: http://company-service
review-service:
  url: http://review-service

server:
  port: 8081

spring:
  application:
    name: company-service

  # Postgres
  datasource:
    url: jdbc:postgresql://postgres:5432/job-portal
    username: admin
    password: password

  jpa:
    database: POSTGRESQL
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    generate-dll: true
    hibernate:
      ddl-auto: update

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false

