server:
  port: 8081

spring:
  application:
    name: company-service
  # H2 Database
  #  h2:
  #    console:
  #      enabled: true
  #  datasource:
  #    url: jdbc:h2:mem:test

  # Postgres
  datasource:
    url: jdbc:postgresql://localhost:5432/job-portal
    username: admin
    password: password

  jpa:
    database: POSTGRESQL
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    generate-dll: true
    hibernate:
      ddl-auto: update

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true