job-service:
  url: http://job-service:8082
company-service:
  url: http://company-service:8081
review-service:
  url: http://review-service:8083

server:
  port: 8081

spring:
  application:
    name: company-service
  # H2 Database
  #  h2:
  #    console:
  #      enabled: true
  #  datasource:
  #    url: jdbc:h2:mem:test

  # Postgres
  datasource:
    url: jdbc:postgresql://postgres_container:5432/job-portal
    username: admin
    password: password

  jpa:
    database: POSTGRESQL
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    generate-dll: true
    hibernate:
      ddl-auto: update

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

eureka:
  client:
    serviceUrl:
      defaultZone: http://service-reg:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

